region: es
dir_name:
  posts: ../posts
  data: data
  models: saved-models
  samples: samples
  images: images
charRNNmodel:
  mode: train
  file_type: titles
  hidden_dim: 256
  num_layers: 1
  input_dropout: 0.1
  recurrent_dropout: 0.1
  epochs: 10
  epoch_slices: 10
  resume_training: True
  sample_size: 5000
  max_len: 100
  step: 5
  batch_size: 256
