region: es
dir_name:
  posts: ../posts
  data: data
  models: saved_models
  samples: samples
  images: plots
charRNNmodel:
  mode: test
  hidden_dim: 256
  num_layers: 1
  epochs: 10
  resume_training: True
  input_dropout: 0.1
  recurrent_dropout: 0.1
  sample_size: 500
  max_len: 100
  step: 5
  batch_size: 256
