dir_name:
  posts: stackoverflow_posts
  data: data
  mappings: mappings
  models: saved_models
dataset:
  name: medium_pt
  training_size: 20000
  validation_size: 10000
  test_size: 10000
xml_extract:
  region: pt
  begin_year: 2015
  begin_month: 1
  read_extra: 0.35
vocabularies:
  keep_tags: 20
  skip_top: 0
  keep_words: 2000
  min_word_freq: 5
  max_word_len: 30
mappings:
  save_word_mapping: True
  save_tag_mapping: True
keras_format:
  max_seq_len: 500
  truncating: pre
  padding: pre
model:
  embedding_dim: 512
  hidden_dim: 512
  num_layers: 1
  bidirectional: False
  input_dropout: 0.2
  recurrent_dropout: 0.2
  batch_size: 128
  epochs: 100
