dir_name:
  posts: stackoverflow_posts
  data: data
  mappings: mappings
dataset:
  name: small_pt
  training_size: 2000
  validation_size: 500
  test_size: 2000
xml_extract:
  region: pt
  begin_year: 2015
  begin_month: 1
  read_extra: 0.35
vocabularies:
  keep_tags: 20
  skip_top: 0
  keep_words: 2000
  min_word_freq: 5
  max_word_len: 30
mappings:
  save_word_mapping: True
  save_tag_mapping: True
keras_format:
  max_seq_len: 500
  truncating: pre
  padding: pre
