dir_name:
  posts: stackoverflow_posts
  data: data
  mappings: mappings
dataset_size:
  training_set: 2000
  validation_set: 500
  test_set: 2000
xml_extract:
  region: pt
  begin_year: 2015
  begin_month: 1
  read_extra: 0.3
data_preprocess:
  keep_tags: 20
  skip_top: 0
  keep_words: 2000
  min_word_freq: 5
  max_word_len: 30
  save_word_mapping: True
  save_tag_mapping: True
