region: en
available_regions:
  - en  # English
  - pt  # Portuguese
  - es  # Spanish
  - ru  # Russian
  - ja  # Japanese
params:
  regions:
    en: normal
    pt: normal
    es: normal
  normal:
    use_bulk_insert: True
    bulk_size: 100000
    insert_answers_body: False
    verbose: True

